### ISSUE TITLE
Cannot resize window on mac

### ISSUE THREAD

**Issue by fransyozef** [cryptoinsightio/cryptoinsight-client#1]
I have a macbookpro 2011 , 13inch. 
The application canvas is bigger than my screen. I tried to resize the window, but it's fixed.

![schermafbeelding 2017-12-25 om 11 57 07](https://user-images.githubusercontent.com/13717081/34338633-fe6b03f0-e96a-11e7-88ad-c3134edf1057.png)

**Comment by cryptoinsightio** [comment]
This is fixed in the next build, the current resize is fixed to a minimum of 1400 by 800, but we'll remove this restriction.
