### ISSUE TITLE
Feature: Allow copy/paste of values when adding a transaction

### ISSUE THREAD

**Issue by cleargif** [cryptoinsightio/cryptoinsight-client#11]
### Please submit the following information for us to be able to accurately fix the issue at hand.

OSX Desktop App

1. Steps to reproduce (i.e. what did I do to get this error)
- From the dashboard click the `Add transaction` button
- In the modal complete sections 1 & 2

On section 3 there are two inputs: Price per XXX and Amount (XXX)
- `cmd + v` does not work in these inputs
- `right click -> paste` does not work in these inputs

2. Operating System
macOS Sierra 10.12.6

3. Resolution
As a user, I want to use general usage patterns like `copy/paste` and `right click` to be available when inputting data of this nature.
 
4. Any additional information (screenshot, etc)
<img width="592" alt="screen shot 2018-01-05 at 22 31 55" src="https://user-images.githubusercontent.com/3668907/34631743-c3bb8664-f269-11e7-87c6-8a333223fa3b.png">

**Comment by cryptoinsightio** [comment]
This should be fixed on the latest build already, do you have version 1.0.0 or 1.0.1?

**Comment by cleargif** [comment]
I have tested both versions now:
- the paste does not work into the value amounts
- and I am unable to copy the `Total Price` field.

**Comment by cryptoinsightio** [comment]
Aha, yes. Copy does not work, paste should work and we'll look into this again. I personally tested using MacOSX High Sierra a few days ago, but will give it another spin.

**Comment by cleargif** [comment]
After restarting my app the `copy/paste` is working nicely 👍 

Question:
On this screen when I add a transaction, step two is adding the date. Step 3 the price and units. 

How do you prefill the price in step 3? Are you using the date / time reference give and looking it up..?  I can't work out if you do.. the price is sometimes nearly spot-on, other times it feels like it is cached in the view from the last transaction I added.

..if this is a feature and you do look it up based on the date.. it is my favorite feature so far! Even if it is off by one or two, it is quick to correct and move on adding more data.

**Comment by cleargif** [comment]
Some screenshots of adding 10 DOGE, buy date `2018-08-01 22:00`.

<img width="434" alt="screen shot 2018-01-06 
at 22 16 02" src="https://user-images.githubusercontent.com/3668907/34644485-915e354c-f32f-11e7-8b14-a907cb04e7b9.png">
<img width="354" alt="screen shot 2018-01-06 at 22 17 44" src="https://user-images.githubusercontent.com/3668907/34644488-9c70b842-f32f-11e7-8b7b-40c59f060d20.png">
<img width="437" alt="screen shot 2018-01-06 at 22 17 55" src="https://user-images.githubusercontent.com/3668907/34644491-a35f1dc4-f32f-11e7-98bd-a971e56a1b83.png">

**Comment by cryptoinsightio** [comment]
When a historical date is selected, we check the prices via our API for the nearest price known to that date. Sometimes the nearest price can be a day - it makes sense I think for us to throw some text that says which date the price is fetched for.

As for the last issue, we've generally capped the amount of decimals, but some tokens just have too many. The price for DOGE does seem correct, see https://coinmarketcap.com/currencies/dogecoin/
