### ISSUE TITLE
Total profit/loss section in Dashbord is incorrect

### ISSUE THREAD

**Issue by gilas551** [cryptoinsightio/cryptoinsight-client#3]
Hi guys, I am using windows 10 version of desktop client and I noticed that total profit/loss section shows a loss of -51.59% when it really should show a loss of about -5%. I hold 2 currencies TKR and BlockCAT. It's probably worth to mention that when my portfolio was total profit/loss was positive everything seemed in order. Total market price and the graph reflects the incorect -51.59 loss.

**Comment by nerdben** [comment]
I had the similar issue (using the MacApp). Added TKR as a second position which lead to wrong numbers in Total Profit/Loss as well as Total Market Price on the dashboard. The values were roughly 10x higher than expected.

**Comment by cryptoinsightio** [comment]
Could you post the steps you took? I'm not able to replicate this.

I noticed MacOS version has a bug when you use the USD pair (we fixed this for the next build), but the Windows version seems OK.

**Comment by gilas551** [comment]
I've added both of these currencies at the day of release, the graph at the dashboard page shows the earliest hour at 12:37 so it probably was around that hour. At first everything seemed fine, I closed the application and returned some time later and suddenly it showed a major decline. The decline fluctuates by a few percentages, but is alway wildly incorrect.

**Comment by cryptoinsightio** [comment]
Aha, CAT has two currencies:

https://coinmarketcap.com/currencies/blockcat/ and https://coinmarketcap.com/currencies/catcoin/, the API that calculates the market data is giving the last one back (which is a lot cheaper).

We will fix this in the next build, thanks :). This is only an issue with currencies with more than symbols.

**Comment by gilas551** [comment]
Thanks, hopefully that will fix the rankings data as well :)

**Comment by cryptoinsightio** [comment]
Fixed with https://github.com/cryptoinsightio/cryptoinsight-client/releases/tag/1.0.1
