### ISSUE TITLE
scrolling doesn't work in several places in win10

### ISSUE THREAD

**Issue by gilas551** [cryptoinsightio/cryptoinsight-client#4]
There are the places where scrolling doesn't work (or atleast im not awhere how it works):
Dashboard:
Portfolio profit/loss section
Top 24h gaining currencies
Transactions:
The main section (sidescrolling doesn't work or the section over enlarged)

**Comment by cryptoinsightio** [comment]
There shouldn't be any scrolling in portfolio profit/loss (on the left pane), the transactions page I'm not 100% sure which section you're talking about? Do you have a screenshot?

**Comment by gilas551** [comment]
![image](https://user-images.githubusercontent.com/31994490/34365163-d6f053e4-ea95-11e7-90a9-66b344d05eea.png)

**Comment by gilas551** [comment]
![image](https://user-images.githubusercontent.com/31994490/34365174-f8aff7a0-ea95-11e7-98da-30e76e07f6e7.png)

**Comment by cryptoinsightio** [comment]
What's your resolution?

**Comment by gilas551** [comment]
1366x768

**Comment by cryptoinsightio** [comment]
Fixed with https://github.com/cryptoinsightio/cryptoinsight-client/releases/tag/1.0.1, if the issue occurs please feel free to open up or reply to this comment.
