### ISSUE TITLE
Instances where words overlap or are cut out in win10

### ISSUE THREAD

**Issue by gilas551** [cryptoinsightio/cryptoinsight-client#5]
Dashboard:
Portfolio profit/loss section (all percentages overlap with words)
Top 24h gaining currencies (the logo of second coin doesn't apear fully)
Currency valuation (one half the words total share and their percentages are cut out)
Market:
the graph (zoom option all aoverlaps with the beginnning of currency name and sometimes the currencie name will overlap with the word from (the latter is dependant not on the lenght of curriency name but rather how high above the dateline curriencies name is placed))
Rankings:
my second curriencies box ovelaps with the words Top Performer, if I had a third curriencie it would probably overlap with the word favourites

**Comment by cryptoinsightio** [comment]
Could you post your resolution as well if possible (a screenshot would help too), we've tested with most resolutions and didn't have this issue.

**Comment by gilas551** [comment]
![image](https://user-images.githubusercontent.com/31994490/34365231-a1010bd8-ea96-11e7-9363-8afa71aaca22.png)

![image](https://user-images.githubusercontent.com/31994490/34365241-c0458622-ea96-11e7-88cc-cb311f978979.png)

![image](https://user-images.githubusercontent.com/31994490/34365252-f074b4bc-ea96-11e7-826a-3f1a6c91634f.png)

![image](https://user-images.githubusercontent.com/31994490/34365264-0e2a2d0c-ea97-11e7-9dd9-a7fecb09b2d5.png)

notice how the coin name is sometimes above and sometimes inline with date options

**Comment by gilas551** [comment]
My resolution is 1366x768

**Comment by cryptoinsightio** [comment]
Fixed with https://github.com/cryptoinsightio/cryptoinsight-client/releases/tag/1.0.1, if the issue occurs please feel free to open up or reply to this comment.
