### ISSUE TITLE
Rankings data is wrong in win10

### ISSUE THREAD

**Issue by gilas551** [cryptoinsightio/cryptoinsight-client#6]
If I set the from date 12/25/2017 and to date 12/26/2017 it shows me a 18% decrease in TKR and 80% decrease in BlockCAT (this is obviously incorrect). But if I set the to date to any future date I get a 5% increase in TKR value and a 12% increase in BlockCAT (despite this the profit/loss value is still in the negative). 
PS: I have bought both of these curriencies on 12/25/2017
PSS: If any of these issues were of value to you guys, consider sending some tokens to this address: 0x6c750712e6BAeb7F5445144219dfcb7cbED2e23d

**Comment by cryptoinsightio** [comment]
Could you tell me which currencies you added at which date so we can reproduce this, and OS if possible.

**Comment by cryptoinsightio** [comment]
Fixed with https://github.com/cryptoinsightio/cryptoinsight-client/releases/tag/1.0.1, if the issue occurs please feel free to open up or reply to this comment.
