### ISSUE TITLE
Full Screen mode on High Sierra OS is not full screen. 

### ISSUE THREAD

**Issue by Stefano04** [cryptoinsightio/cryptoinsight-client#7]
<img width="1280" alt="schermata 2017-12-26 alle 20 51 08" src="https://user-images.githubusercontent.com/32912719/34363789-6e8d6ae6-ea7f-11e7-8f67-aaccd6cf005c.png">

**Comment by Stefano04** [comment]
This is a full-screen screenshot of how the window looks like. The window doesn't resize correctly.

**Comment by cryptoinsightio** [comment]
What's your resolution? I think at a very small resolution it starts scrolling sideways, we'll get this changed so it fits (but at a loss of column width and/or font size)

**Comment by Stefano04** [comment]
MacBook Pro 13', default resolution as per system preferences.
<img width="1280" alt="schermata 2017-12-26 alle 22 04 25" src="https://user-images.githubusercontent.com/32912719/34364711-ca333d18-ea88-11e7-8862-09a1c852c433.png">
![Uploading Schermata 2017-12-26 alle 22.04.14.png…]()

**Comment by cryptoinsightio** [comment]
Okay thanks, we'll have a look and fix the table. Thanks.

**Comment by cryptoinsightio** [comment]
We have identified the issue and will fix this with the next build, it's because our app requires a certain minimum resolution but we've put that a little bit too high (1600x900), so most laptops would have an issue rendering.

**Comment by cryptoinsightio** [comment]
Fixed with https://github.com/cryptoinsightio/cryptoinsight-client/releases/tag/1.0.1, if the issue occurs please feel free to open up or reply to this comment.
